### ISSUE TITLE
Prepare chapter 1 content

### ISSUE THREAD

**Issue by MohammadMahdi-Akhondi** [ftg-iran/didp-persian#1]
Preparing the content of the first chapter (Introduction To OOP)

**Comment by khalil-farashiani** [comment]
سلام ممنون از مشارکتتون. لطفا یه تاریخ برای اتمام آماده سازی بدید.

**Comment by MohammadMahdi-Akhondi** [comment]
سلام نهایتا تا آخر همین هفته تمام میشه.
