### ISSUE TITLE
Translation of Introduction to OOP

### ISSUE THREAD

**Issue by SepehrRasouli** [ftg-iran/didp-persian#11]
سلام، آیا من میتونم ترجمه ی بخش یک، Introduction to OOP رو انجام بدم ؟

**Comment by khalil-farashiani** [comment]
بله حتماً، فقط یک تاریخ حدودی برای ترجمه اعلام کنید

**Comment by SepehrRasouli** [comment]
من حدودا تا آخر هفته ی بعدی ترجمه رو کاملا تموم میکنم
