### ISSUE TITLE
ترجمه بخش Factory Method

### ISSUE THREAD

**Issue by mmdbalkhi** [ftg-iran/didp-persian#15]
ترجمه بخش Factory Method ان‌شاءالله تا  ۲۰ شهریور

**Comment by khalil-farashiani** [comment]
سلام شروع کنید فقط فایل ترجمه رو داخل فایلی به اسم FactoryMethod_README.md

**Comment by mmdbalkhi** [comment]
@khalil-farashiani در کدوم دایرکتوری قرارش بدم؟

**Comment by khalil-farashiani** [comment]
در دایرکتوری فصل چهارم catalog of design patterns
