### ISSUE TITLE
ترجمه بخش singleton 

### ISSUE THREAD

**Issue by amirhosein-kia-darbandsary** [ftg-iran/didp-persian#19]
I prefer to delegate and participate with you guys

**Comment by khalil-farashiani** [comment]
Thanks for your participation, please give an approximate date for the completion of the translation.

**Comment by amirhosein-kia-darbandsary** [comment]
حداکثر 17 شهریور

**Comment by khalil-farashiani** [comment]
Ok. please put the translation in a file called  Singleton.md in the "Catalog Of Design Patterns" directory.
