### ISSUE TITLE
Moving to official translation repository

### ISSUE THREAD

**Issue by neochief** [ftg-iran/didp-persian#21]
Hi!

I'm the author of the book that you're translating. Translating everything on GitHub violates my copyright, and I don't appreciate it. It violates GitHub ToS, and your entire project can suffer from this.

If you guys want to keep translating the book, why don't you contribute to the official Persian translation instead? I do all the translations through Crowdin service. There's a Persian branch that can be translated by anyone who applies as a translator. You'll get access to the actual source, not the one you managed to scrap from the book files. By translating it officially, you will let me release it along with the other language versions on refactoring.guru, and it will be freely available to anyone worldwide.

**Comment by khalil-farashiani** [comment]
Hi
we understand your concern about this issue. To show our goodwill, we removed the book link from the GitHub repository.
We are happy with your suggestion and we eagerly accept it. Please tell us what we should do to add the Persian(Farsi) translation to the refactoring guru website.
we want to the translations remain on our team's GitHub in addition to the official guru website, at the beginning of the main README we tell readers of the translation to use the guru website to read the translation.

**Comment by neochief** [comment]
Visit this link and press "Translate all": https://crowdin.com/project/refactoringguru/fa

This will redirect you to the page where you can create a Crowdin account and then submit a request to join the translation team (that I'm going to approve for all of your team members).

> we want to the translations remain on our team's GitHub in addition to the official guru website, at the beginning of the main README we tell readers of the translation to use the guru website to read the translation.

Sorry, but having the content here will not work for two reasons:

1. People treat stuff published on Github as if no one owns it. You won't believe how often I have to deal with unauthorized usage of my content. I don't want to leave a loophole here on Github.

2. I will need to spend some of my personal time integrating this translation into the website (there's not RTL language support yet). I won't be able to compensate for this time through the book sales, so the only incentive I get from doing this is the added content on refactoring.guru, which may improve the website's search rankings. If you publish the same content on Github, search engines will penalize my website for duplication.

I can only guess why you are insisting on still publishing the content here. You can leave this repository's front page, redirecting to the Farsi version of refactoring.guru and the Crowdin's Farsi branch, though, if your main goal is to claim credits for the translation. From my side, I can also guarantee you to keep your credits on the website for the Farsi version. If the motivation is different, please let me know and we'll figure something out.

**Comment by khalil-farashiani** [comment]
Ok, I applied on the website with an account named Khalil Farasiniani
Our problem is that our team has no experience working with crowdin yet.
We ask you to allow the translation to continue on Github. After the translation is finished, all the content will be transferred to crowdin, and in the main README of the translation of this book on Github will be the translation contributors and the guru's official website address. In this way, I think the problem of repetitive content will also be solved.
Of course, if you have a better offer, we will sincerely accept it

**Comment by neochief** [comment]
Working in Crowdin is not complicated; it's a tool made for non-technical people. You and your team won't have much trouble figuring it out. I'll send you an email to explain the ropes and where to begin.

**Comment by khalil-farashiani** [comment]
Ok I'll check it,
