### ISSUE TITLE
درخواست ترجمه بخش Abstract factoy

### ISSUE THREAD

**Issue by zoha-shobbar** [ftg-iran/didp-persian#32]
سلام و احترام 
میخواستم درخواست بدم که بخش Abstract factoy رو ترجمه کنم. ممنون میشم اجازه ش رو بدید
با تشکر

**Comment by khalil-farashiani** [comment]
سلام حتما، به ریپوی پرایوت دعوتتون کردم 🌹

**Comment by zoha-shobbar** [comment]
سپاس بیکران
