### ISSUE TITLE
درخواست ترجمه بخش Builder

### ISSUE THREAD

**Issue by emadtroll** [ftg-iran/didp-persian#33]
سلام وقت به خیر. عماد رضوی هستم توسعه دهنده اندروید. حدود شش سالی هست برنامه نویسی می کنم. درخواست ترجمه این بخش رو دارم. خوشحال میشم بتونم در این حرکت مثبت همراهی کنم با سایر عزیزان.

**Comment by khalil-farashiani** [comment]
سلام حتما ممنون از مشارکتتون لطفا یک تاریخ حدودی برای اتمام ترجمتون بفرمایید

**Comment by emadtroll** [comment]
لطف می کنید. من سعی می کنم تا ۱۰ روز آتی ترجمه خودم رو داشته باشم. نهایتا
فرض بفرمایید تا آخر این ماه.

**Comment by khalil-farashiani** [comment]
خیلی ممنون 🌹  شما رو به ریپو خصوصی اینوایت دادم

**Comment by emadtroll** [comment]
سلام. ببخشید باعث زحمت شما میشم. امکانش هست مجددا لینک دعوت رو ارسال
بفرمایید؟

**Comment by khalil-farashiani** [comment]
سلام من مجدد دعوتتون کردم از قسمت نوتیفیکیشن گیتهابتون میتونید درخواست من رو قبول کنید
![image](https://user-images.githubusercontent.com/70664202/196090642-939623dc-8a52-48a4-aef2-32e10da8558e.png)
