### ISSUE TITLE
درخواست ترجمه بخش Facade

### ISSUE THREAD

**Issue by matinwd** [ftg-iran/didp-persian#34]
سلام متین نوروزی هستم، برنامه نویس PHP Laravel و 6 سال سابقه کد نویسی وب دارم. مایلم در صورت امکان به ترجمه پترن Facade این کتاب کمک کنم.
تا 10 روز میتوانم ترجمه این بخش رو کامل کنم

**Comment by khalil-farashiani** [comment]
سلام عذر میخوام بابت اینکه دیر پاسخ میدم.
 حتما به ریپو خصوصی دعوتتون کردم .
